[bar.default]
center = [ "active_window" ]
end = [ "media", "network", "volume", "bluetooth", "battery", "tray", "notifications", "control-center", "session" ]
margin_edge = 0
margin_ends = 0
panel_overlap = 3
start = [ "workspaces", "clock" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 640.0
    cy = 601.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[shell]
clipboard_enabled = false
show_location = false

[wallpaper]
enabled = false

[widget.clock]
format = "{:%A, %B %d | %H:%M}"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false